{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "eratemanager.fullname" . }}-refresh
  labels:
    {{- include "eratemanager.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "eratemanager.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "eratemanager.serviceAccountName" . }}
          containers:
            - name: refresh-pdf
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["cemc-rates", "refresh-pdf"]
              {{- if .Values.persistence.enabled }}
              volumeMounts:
                - name: cache-volume
                  mountPath: {{ .Values.persistence.mountPath }}
              {{- end }}
          {{- if .Values.persistence.enabled }}
          volumes:
            - name: cache-volume
              {{- if .Values.persistence.existingClaim }}
              persistentVolumeClaim:
                claimName: {{ .Values.persistence.existingClaim }}
              {{- else }}
              persistentVolumeClaim:
                claimName: {{ include "eratemanager.fullname" . }}-pvc
              {{- end }}
          {{- end }}
{{- end }}
