apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eratemanager.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.persistence.enabled }}
  # Use Recreate strategy when using ReadWriteOnce PVC to avoid Multi-Attach errors
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "eratemanager.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "eratemanager.name" . }}
    spec:
      {{- if and .Values.imagePullSecrets (gt (len .Values.imagePullSecrets) 0) }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
      {{- end }}
      {{- end }}
      containers:
        - name: eratemanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.app.port }}"
            - name: ERATEMANAGER_DB_DRIVER
              value: {{ .Values.db.driver | quote }}
            - name: ERATEMANAGER_DB_DSN
              value: {{ .Values.db.dsn | quote }}

          ports:
            - containerPort: {{ .Values.app.port }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "eratemanager.fullname" . }}-data
