apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eratemanager.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "eratemanager.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "eratemanager.name" . }}
    spec:
      imagePullSecrets:
      {{- if .Values.imagePullSecrets }}
      {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
      {{- end }}
      {{- end }}
      containers:
        - name: eratemanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.app.port }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "eratemanager.fullname" . }}-data
