{{- if .Values.gatewayAPI.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "eratemanager.fullname" . }}
  labels:
    {{- include "eratemanager.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gatewayAPI.gatewayName }}
      namespace: {{ .Values.gatewayAPI.gatewayNamespace }}
  hostnames:
    - "{{ .Values.gatewayAPI.hostname }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "eratemanager.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
