apiVersion: v1
kind: Service
metadata:
  name: {{ include "eratemanager.fullname" . }}
  labels:
    app: {{ include "eratemanager.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "eratemanager.name" . }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
