{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eratemanager.serviceAccountName" . }}
  labels:
    {{- include "eratemanager.labels" . | nindent 4 }}
{{- end }}
