{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "eratemanager.fullname" . }}
  labels:
    app: {{ include "eratemanager.name" . }}
    {{- range $k, $v := .Values.monitoring.serviceMonitor.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespaceSelector:
    matchNames:
      - {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- else }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "eratemanager.name" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
{{- end }}
