definitions:
  internal_api.ProviderDTO:
    properties:
      key:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v2/electric-rates/{providerKey}/{action}:
    get:
      description: Get residential rates, PDF, or force refresh for a provider
      parameters:
      - description: Provider Key
        in: path
        name: providerKey
        required: true
        type: string
      - description: Action (residential, pdf, refresh)
        in: path
        name: action
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get electric rates or refresh
      tags:
      - electric
  /api/v2/electric-rates/providers:
    get:
      description: Get a list of all available electric providers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_api.ProviderDTO'
            type: array
      summary: List electric providers
      tags:
      - electric
  /api/v2/water-rates/{providerKey}:
    get:
      description: Get water rates or force refresh for a provider
      parameters:
      - description: Provider Key
        in: path
        name: providerKey
        required: true
        type: string
      - description: Action (refresh)
        in: path
        name: action
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get water rates or refresh
      tags:
      - water
  /api/v2/water-rates/providers:
    get:
      description: Get a list of all available water providers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_api.ProviderDTO'
            type: array
      summary: List water providers
      tags:
      - water
swagger: "2.0"
